[build]
  command = "npm install" # Only install dependencies, no build step for functions themselves
  publish = "public"      # A publish directory is still required. Create an empty 'public' folder
                          # in your root if you don't have a frontend to deploy.

[functions]
  directory = "netlify/functions" # This tells Netlify where your functions are located

[[redirects]]
  from = "/api/tasks/*"         # Requests to /api/tasks/anything
  to = "/.netlify/functions/tasks" # Route them to your tasks.js function
  status = 200
  force = true

[[redirects]]
  from = "/api/gemini/*"        # Requests to /api/gemini/anything
  to = "/.netlify/functions/gemini" # Route them to your gemini.js function
  status = 200
  force = true

[dev]
  command = "netlify dev" # Use Netlify CLI for local development with functions
  port = 5000