[build]
  command = "npm install" # Just install dependencies for functions
  publish = "public"      # Or wherever your *frontend* static files are, if any.
                          # For pure API, this might not be relevant, but a publish dir is required.

[functions]
  directory = "netlify/functions" # Tell Netlify where your functions are located

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" # Redirect to your Netlify Function(s)
  status = 200
  force = true