[build]
  command = "npm install && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/src/server.js"
  status = 200
  force = true